.\" Manpage for kevlar.
.\" Contact Titus to correct errors or typos.
.TH man 8 "01 April 2019" "1.0" "kevlar man page"
.SH NAME
kevlar - reference-free variant discovery in large eukaryotic genomes 
.SH SYNOPSIS
 kevlar [-h] [-v] [-l F] [--tee] COMMAND
.SH DESCRIPTION
Welcome to kevlar, software for predicting de novo genetic variants without mapping reads to a reference genome! 
kevlar's k-mer abundance based method calls single nucleotide variants (SNVs), multinucleotide variants (MNVs), 
insertion/deletion variants (indels), and structural variants (SVs) simultaneously with a single simple model. 
This software is free for use under the MIT license.
.SH OPTIONS
-h,   --help       shows original manual, no COMMAND needed.

-v,   --version    show program's version number and exit.

-l F, --logfile F  log file for diagnostic messages, warnings, and errors

--tee              write diagnostic output to logfile AND terminal (stderr)

.SH COMMANDS
  alac :

  assemble :

  augment :

  call :

  count :

  dist :

  filter :

  gentrio :

  localize :

  mutate : 

  novel :

  partition :

  simlike :

  split :

  unband :

  varfilter :

.SH FILES

.SH SEE ALSO
 
.SH BUGS
No known bugs.
.SH AUTHOR
Titus C Brown
